// flow-typed signature: 805aeaa158a221851105f0f39990c198
// flow-typed version: <<STUB>>/luna_v^1.5.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'luna'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'luna' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'luna/dist/createStore' {
  declare module.exports: any;
}

declare module 'luna/dist/index' {
  declare module.exports: any;
}

declare module 'luna/dist/interfaces' {
  declare module.exports: any;
}

declare module 'luna/dist/Store' {
  declare module.exports: any;
}

declare module 'luna/dist/util/combineReducers' {
  declare module.exports: any;
}

declare module 'luna/dist/util/isAction' {
  declare module.exports: any;
}

declare module 'luna/karma.conf' {
  declare module.exports: any;
}

declare module 'luna/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'luna/dist/createStore.js' {
  declare module.exports: $Exports<'luna/dist/createStore'>;
}
declare module 'luna/dist/index.js' {
  declare module.exports: $Exports<'luna/dist/index'>;
}
declare module 'luna/dist/interfaces.js' {
  declare module.exports: $Exports<'luna/dist/interfaces'>;
}
declare module 'luna/dist/Store.js' {
  declare module.exports: $Exports<'luna/dist/Store'>;
}
declare module 'luna/dist/util/combineReducers.js' {
  declare module.exports: $Exports<'luna/dist/util/combineReducers'>;
}
declare module 'luna/dist/util/isAction.js' {
  declare module.exports: $Exports<'luna/dist/util/isAction'>;
}
declare module 'luna/karma.conf.js' {
  declare module.exports: $Exports<'luna/karma.conf'>;
}
declare module 'luna/webpack.config.js' {
  declare module.exports: $Exports<'luna/webpack.config'>;
}
