// flow-typed signature: 402b21eae0fcd8b701cb6e2b1121f918
// flow-typed version: <<STUB>>/lato-font_v^3.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lato-font'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lato-font' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lato-font/bin/rename' {
  declare module.exports: any;
}

declare module 'lato-font/gulp-tasks/styles/build' {
  declare module.exports: any;
}

declare module 'lato-font/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lato-font/bin/rename.js' {
  declare module.exports: $Exports<'lato-font/bin/rename'>;
}
declare module 'lato-font/gulp-tasks/styles/build.js' {
  declare module.exports: $Exports<'lato-font/gulp-tasks/styles/build'>;
}
declare module 'lato-font/gulpfile.js' {
  declare module.exports: $Exports<'lato-font/gulpfile'>;
}
