// flow-typed signature: eca9a491a6f24cd766e82a2956e4b3e9
// flow-typed version: <<STUB>>/react-markdownit_v^2.5.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-markdownit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-markdownit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-markdownit/dist/example/app' {
  declare module.exports: any;
}

declare module 'react-markdownit/dist/example/vendor' {
  declare module.exports: any;
}

declare module 'react-markdownit/lib/example/index' {
  declare module.exports: any;
}

declare module 'react-markdownit/lib/example/Readme' {
  declare module.exports: any;
}

declare module 'react-markdownit/lib/flatmap' {
  declare module.exports: any;
}

declare module 'react-markdownit/lib/html2react' {
  declare module.exports: any;
}

declare module 'react-markdownit/lib/index' {
  declare module.exports: any;
}

declare module 'react-markdownit/lib/react-markdownit.example' {
  declare module.exports: any;
}

declare module 'react-markdownit/webpack.build-docs.config' {
  declare module.exports: any;
}

declare module 'react-markdownit/webpack.develop.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-markdownit/dist/example/app.js' {
  declare module.exports: $Exports<'react-markdownit/dist/example/app'>;
}
declare module 'react-markdownit/dist/example/vendor.js' {
  declare module.exports: $Exports<'react-markdownit/dist/example/vendor'>;
}
declare module 'react-markdownit/lib/example/index.js' {
  declare module.exports: $Exports<'react-markdownit/lib/example/index'>;
}
declare module 'react-markdownit/lib/example/Readme.js' {
  declare module.exports: $Exports<'react-markdownit/lib/example/Readme'>;
}
declare module 'react-markdownit/lib/flatmap.js' {
  declare module.exports: $Exports<'react-markdownit/lib/flatmap'>;
}
declare module 'react-markdownit/lib/html2react.js' {
  declare module.exports: $Exports<'react-markdownit/lib/html2react'>;
}
declare module 'react-markdownit/lib/index.js' {
  declare module.exports: $Exports<'react-markdownit/lib/index'>;
}
declare module 'react-markdownit/lib/react-markdownit.example.js' {
  declare module.exports: $Exports<'react-markdownit/lib/react-markdownit.example'>;
}
declare module 'react-markdownit/webpack.build-docs.config.js' {
  declare module.exports: $Exports<'react-markdownit/webpack.build-docs.config'>;
}
declare module 'react-markdownit/webpack.develop.config.js' {
  declare module.exports: $Exports<'react-markdownit/webpack.develop.config'>;
}
