// flow-typed signature: 61f1e4c0676abf59c49a5b21e7f97ec6
// flow-typed version: <<STUB>>/luna-saga_v^3.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'luna-saga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'luna-saga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'luna-saga/dist/effects/effectsHelpers' {
  declare module.exports: any;
}

declare module 'luna-saga/dist/effects/interfaces' {
  declare module.exports: any;
}

declare module 'luna-saga/dist/effects/isEffect' {
  declare module.exports: any;
}

declare module 'luna-saga/dist/helpers' {
  declare module.exports: any;
}

declare module 'luna-saga/dist/index' {
  declare module.exports: any;
}

declare module 'luna-saga/dist/interfaces' {
  declare module.exports: any;
}

declare module 'luna-saga/dist/Saga' {
  declare module.exports: any;
}

declare module 'luna-saga/dist/sagaConnect' {
  declare module.exports: any;
}

declare module 'luna-saga/dist/util/isAction' {
  declare module.exports: any;
}

declare module 'luna-saga/dist/util/isArray' {
  declare module.exports: any;
}

declare module 'luna-saga/dist/util/isCallback' {
  declare module.exports: any;
}

declare module 'luna-saga/dist/util/isFunction' {
  declare module.exports: any;
}

declare module 'luna-saga/dist/util/isIterator' {
  declare module.exports: any;
}

declare module 'luna-saga/dist/util/isNull' {
  declare module.exports: any;
}

declare module 'luna-saga/dist/util/isPromise' {
  declare module.exports: any;
}

declare module 'luna-saga/dist/util/isUndefined' {
  declare module.exports: any;
}

declare module 'luna-saga/dist/util/Sym' {
  declare module.exports: any;
}

declare module 'luna-saga/karma.conf' {
  declare module.exports: any;
}

declare module 'luna-saga/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'luna-saga/dist/effects/effectsHelpers.js' {
  declare module.exports: $Exports<'luna-saga/dist/effects/effectsHelpers'>;
}
declare module 'luna-saga/dist/effects/interfaces.js' {
  declare module.exports: $Exports<'luna-saga/dist/effects/interfaces'>;
}
declare module 'luna-saga/dist/effects/isEffect.js' {
  declare module.exports: $Exports<'luna-saga/dist/effects/isEffect'>;
}
declare module 'luna-saga/dist/helpers.js' {
  declare module.exports: $Exports<'luna-saga/dist/helpers'>;
}
declare module 'luna-saga/dist/index.js' {
  declare module.exports: $Exports<'luna-saga/dist/index'>;
}
declare module 'luna-saga/dist/interfaces.js' {
  declare module.exports: $Exports<'luna-saga/dist/interfaces'>;
}
declare module 'luna-saga/dist/Saga.js' {
  declare module.exports: $Exports<'luna-saga/dist/Saga'>;
}
declare module 'luna-saga/dist/sagaConnect.js' {
  declare module.exports: $Exports<'luna-saga/dist/sagaConnect'>;
}
declare module 'luna-saga/dist/util/isAction.js' {
  declare module.exports: $Exports<'luna-saga/dist/util/isAction'>;
}
declare module 'luna-saga/dist/util/isArray.js' {
  declare module.exports: $Exports<'luna-saga/dist/util/isArray'>;
}
declare module 'luna-saga/dist/util/isCallback.js' {
  declare module.exports: $Exports<'luna-saga/dist/util/isCallback'>;
}
declare module 'luna-saga/dist/util/isFunction.js' {
  declare module.exports: $Exports<'luna-saga/dist/util/isFunction'>;
}
declare module 'luna-saga/dist/util/isIterator.js' {
  declare module.exports: $Exports<'luna-saga/dist/util/isIterator'>;
}
declare module 'luna-saga/dist/util/isNull.js' {
  declare module.exports: $Exports<'luna-saga/dist/util/isNull'>;
}
declare module 'luna-saga/dist/util/isPromise.js' {
  declare module.exports: $Exports<'luna-saga/dist/util/isPromise'>;
}
declare module 'luna-saga/dist/util/isUndefined.js' {
  declare module.exports: $Exports<'luna-saga/dist/util/isUndefined'>;
}
declare module 'luna-saga/dist/util/Sym.js' {
  declare module.exports: $Exports<'luna-saga/dist/util/Sym'>;
}
declare module 'luna-saga/karma.conf.js' {
  declare module.exports: $Exports<'luna-saga/karma.conf'>;
}
declare module 'luna-saga/webpack.config.js' {
  declare module.exports: $Exports<'luna-saga/webpack.config'>;
}
