// flow-typed signature: b089f9a796a3f2092e2b8a217b5d0a64
// flow-typed version: <<STUB>>/github-markdown-css_v^2.8.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'github-markdown-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'github-markdown-css' {
  declare module.exports: any;
}
