// flow-typed signature: 3c8f8c28e1d6bca9c0b6776d0afb3605
// flow-typed version: <<STUB>>/layout-components_v^2.7.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'layout-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'layout-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'layout-components/dist/example/app' {
  declare module.exports: any;
}

declare module 'layout-components/dist/example/index' {
  declare module.exports: any;
}

declare module 'layout-components/dist/example/Readme' {
  declare module.exports: any;
}

declare module 'layout-components/dist/example/server' {
  declare module.exports: any;
}

declare module 'layout-components/dist/example/vendor' {
  declare module.exports: any;
}

declare module 'layout-components/dist/Flex-column.example' {
  declare module.exports: any;
}

declare module 'layout-components/dist/Flex-fill.example' {
  declare module.exports: any;
}

declare module 'layout-components/dist/Flex-row.example' {
  declare module.exports: any;
}

declare module 'layout-components/dist/Flex.example' {
  declare module.exports: any;
}

declare module 'layout-components/dist/Flex' {
  declare module.exports: any;
}

declare module 'layout-components/dist/FlexHide' {
  declare module.exports: any;
}

declare module 'layout-components/dist/FlexItem' {
  declare module.exports: any;
}

declare module 'layout-components/dist/FlexSpacer' {
  declare module.exports: any;
}

declare module 'layout-components/dist/index' {
  declare module.exports: any;
}

declare module 'layout-components/dist/Responsive' {
  declare module.exports: any;
}

declare module 'layout-components/dist/Row' {
  declare module.exports: any;
}

declare module 'layout-components/dist/style-globals' {
  declare module.exports: any;
}

declare module 'layout-components/dist/Width' {
  declare module.exports: any;
}

declare module 'layout-components/webpack.build-docs.config' {
  declare module.exports: any;
}

declare module 'layout-components/webpack.build-static-docs.config' {
  declare module.exports: any;
}

declare module 'layout-components/webpack.develop.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'layout-components/dist/example/app.js' {
  declare module.exports: $Exports<'layout-components/dist/example/app'>;
}
declare module 'layout-components/dist/example/index.js' {
  declare module.exports: $Exports<'layout-components/dist/example/index'>;
}
declare module 'layout-components/dist/example/Readme.js' {
  declare module.exports: $Exports<'layout-components/dist/example/Readme'>;
}
declare module 'layout-components/dist/example/server.js' {
  declare module.exports: $Exports<'layout-components/dist/example/server'>;
}
declare module 'layout-components/dist/example/vendor.js' {
  declare module.exports: $Exports<'layout-components/dist/example/vendor'>;
}
declare module 'layout-components/dist/Flex-column.example.js' {
  declare module.exports: $Exports<'layout-components/dist/Flex-column.example'>;
}
declare module 'layout-components/dist/Flex-fill.example.js' {
  declare module.exports: $Exports<'layout-components/dist/Flex-fill.example'>;
}
declare module 'layout-components/dist/Flex-row.example.js' {
  declare module.exports: $Exports<'layout-components/dist/Flex-row.example'>;
}
declare module 'layout-components/dist/Flex.example.js' {
  declare module.exports: $Exports<'layout-components/dist/Flex.example'>;
}
declare module 'layout-components/dist/Flex.js' {
  declare module.exports: $Exports<'layout-components/dist/Flex'>;
}
declare module 'layout-components/dist/FlexHide.js' {
  declare module.exports: $Exports<'layout-components/dist/FlexHide'>;
}
declare module 'layout-components/dist/FlexItem.js' {
  declare module.exports: $Exports<'layout-components/dist/FlexItem'>;
}
declare module 'layout-components/dist/FlexSpacer.js' {
  declare module.exports: $Exports<'layout-components/dist/FlexSpacer'>;
}
declare module 'layout-components/dist/index.js' {
  declare module.exports: $Exports<'layout-components/dist/index'>;
}
declare module 'layout-components/dist/Responsive.js' {
  declare module.exports: $Exports<'layout-components/dist/Responsive'>;
}
declare module 'layout-components/dist/Row.js' {
  declare module.exports: $Exports<'layout-components/dist/Row'>;
}
declare module 'layout-components/dist/style-globals.js' {
  declare module.exports: $Exports<'layout-components/dist/style-globals'>;
}
declare module 'layout-components/dist/Width.js' {
  declare module.exports: $Exports<'layout-components/dist/Width'>;
}
declare module 'layout-components/webpack.build-docs.config.js' {
  declare module.exports: $Exports<'layout-components/webpack.build-docs.config'>;
}
declare module 'layout-components/webpack.build-static-docs.config.js' {
  declare module.exports: $Exports<'layout-components/webpack.build-static-docs.config'>;
}
declare module 'layout-components/webpack.develop.config.js' {
  declare module.exports: $Exports<'layout-components/webpack.develop.config'>;
}
